apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting-app
        image: yourdockerhubusername/greeting-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: greeting-app
